version: 0.2
 
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=151803697644.dkr.ecr.us-east-2.amazonaws.com/hello-world
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - AWS_ACCOUNT_ID=151803697644
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker login -u thilina950 -p Abcd@9876
      - docker build -t $REPOSITORY_URI:latest .
      #- docker login -u thilina950 -p Abcd@9876
      #- docker build -t hello-world:latest .
      #- docker tag hello-world:latest 151803697644.dkr.ecr.us-east-2.amazonaws.com/hello-world:latest
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG            
      - printf '151803697644.dkr.ecr.us-east-2.amazonaws.com/hello-world: latest'
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)    
      - printf {"name":"container_name","imageUri":"151803697644.dkr.ecr.us-east-2.amazonaws.com/hello-world:latest"} > imageDetail.json
      #- printf '{"CONTAINER_NAME":"%s"}' 151803697644.dkr.ecr.us-east-2.amazonaws.com/hello-world:latest  > imageDetail.json
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      #- printf '[{"name":"CONTAINER_NAME","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG  > imageDetail.json
      - sed -i 's/<APP_NAME>/'$IMAGE_REPO_NAME'/g' appspec.yml taskdef.json
      - sed -i 's/<SERVICE_PORT>/'$SERVICE_PORT'/g' appspec.yml taskdef.json
      - sed -i 's/<AWS_ACCOUNT_ID>/'$AWS_ACCOUNT_ID'/g' taskdef.json
      - sed -i 's/<MEMORY_RESV>/'$MEMORY_RESV'/g' taskdef.json
      - sed -i 's/<IMAGE_NAME>/'$AWS_ACCOUNT_ID'\.dkr\.ecr\.'us-east-2'\.amazonaws.com\/'$IMAGE_REPO_NAME'\:'$IMAGE_TAG'/g' taskdef.json
artifacts:
  files: 
    - imageDetail.json
    - appspec.yml
    - taskdef.json
